spring:
  main:
    web-application-type: none
    allow-bean-definition-overriding: true
  application:
    ui:
      title: "SoftWeb"
  datasource:
    url: jdbc:mariadb://45.67.35.2:3306/softwebdb
    username: softweb_admin
    password: SoftWUser
    driver-class-name: org.mariadb.jdbc.Driver
    full-url: "jdbc:mariadb://45.67.35.2:3306/softwebdb?user=softweb_admin&password=SoftWUser"
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

connections:
  ftp:
    server: "45.67.35.2"
    port: 21
    username: "softwebftp"
    password: "SoftWUser"

