spring:
  main:
    web-application-type: none
  application:
    ui:
      title: "SoftWeb"
  datasource:
    url: jdbc:mariadb://45.67.35.2:3306/softwebdb
    username: softweb_admin
    password: SoftWUser
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

connections:
  ftp:
    url: 45.67.35.2
    port: 21
    username: newftpuser
    password: ftp

