package com.softweb.desktop.database.entity;

import lombok.*;
import org.springframework.transaction.annotation.Transactional;

import javax.persistence.*;
import java.util.Date;
import java.util.Set;

/**
 * Entity class Developer contains data of developers, what is published applications.
 *
 * It has generated id and data for authentication in system.
 *
 * Also Application class has field, which are referenced with other entity class
 * (published applications).
 *
 * @author Максимчук И.
 * @version 1.0
 */
@Getter
@Setter
@RequiredArgsConstructor
@Entity
@Table(name = "developer")
@AllArgsConstructor
@Transactional
public class Developer {

    /**
     * Autogenerated ID
     */
    @Id
    @Column(name = "id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Developer's username that identify him
     */
    @Column(name = "username")
    private String username;

    /**
     * Full name contains information about developer's full name or company name
     */
    @Column(name = "fullname")
    private String fullName;

    /**
     * Developer's password for authorization
     */
    @Column(name = "password")
    private String password;

    /**
     * Admin flag allows developer manage others applications and developers
     */
    @Column(name = "is_admin")
    private boolean isAdmin;

    /**
     * Last Entered has information about developer's history of entering.
     */
    @Column(name = "last_entered")
    private Date lastEntered;

    /**
     * List of developer's published applications
     */
    @OneToMany(mappedBy = "developer", fetch = FetchType.EAGER)
    private Set<Application> applications;

    @Override
    public String toString() {
        return "Developer{" +
                "id=" + id +
                ", username='" + username + '\'' +
                ", fullName='" + fullName + '\'' +
                ", password='" + password + '\'' +
                ", is_admin=" + isAdmin +
                ", last_entered=" + lastEntered +
                '}';
    }
}
