package com.softweb.desktop.database.entity;

import lombok.*;

import javax.persistence.*;

/**
 * Entity class Installers contains data of application's installers for different OS.
 *
 * It has generated id, path to installer, it version and size.
 *
 * Also Application class has field, which are referenced with other entity class
 * (referenced application and supported OS).
 *
 * @author Максимчук И.
 * @version 1.0
 */
@Entity
@Table(name = "installer")
@AllArgsConstructor
@Getter
@Setter
@RequiredArgsConstructor
public class Installer {

    /**
     * Autogenerated ID
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    /**
     * Referenced application
     */
    @ManyToOne
    @JoinColumn(name = "application_id")
    private Application application;

    /**
     * Supported operating system
     */
    @ManyToOne
    @JoinColumn(name = "system_id")
    private OperatingSystem system;

    /**
     * Installer path contains URL of installer file
     */
    @Column(name = "path")
    private String installerPath;

    /**
     * Version of application installer
     */
    @Column(name = "version")
    private String version;

    /**
     * Size of application installer (bytes)
     */
    @Column(name = "size")
    private int size;

    @Override
    public String toString() {
        return "ApplicationsSystems{" +
                "id=" + id +
                ", system=" + system +
                ", installerPath='" + installerPath + '\'' +
                ", version='" + version + '\'' +
                ", size=" + size +
                '}';
    }
}
